package io.factry.historian.gateway;

import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.DefaultValue;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Description;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormCategory;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormField;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Label;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.NonSecret;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Required;
import com.inductiveautomation.ignition.gateway.web.nav.FormFieldType;

public record FactryHistorianConfig(
        @FormCategory("Connection")
        @Label("Token*")
        @FormField(FormFieldType.TEXTAREA)
        @DefaultValue("")
        @Required
        @NonSecret
        @Description("Collector token generated by Factry Historian. Connection settings (host, port, collector ID) are extracted automatically.")
        String token,

        @FormCategory("Connection")
        @Label("Use TLS")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Use TLS for the gRPC connection. Leave unchecked for plaintext connections (e.g. local test servers).")
        boolean useTls,

        @FormCategory("Connection")
        @Label("Skip TLS Verification")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Disable TLS certificate verification. Use only for testing with self-signed certificates.")
        boolean skipTlsVerification,

        @FormCategory("Connection")
        @Label("Custom CA Certificate (PEM)")
        @FormField(FormFieldType.TEXTAREA)
        @DefaultValue("")
        @NonSecret
        @Description("Optional. Paste one or more PEM-encoded CA certificates (or a self-signed server certificate) "
                + "to trust in addition to the system and bundled Factry CAs. Use this for a Historian fronted by an "
                + "internal/enterprise CA or a self-signed certificate, instead of disabling verification. "
                + "Applies only when TLS is on and 'Skip TLS Verification' is off. The certificate's host name must "
                + "still match the configured host.")
        String customCaCert,

        @FormCategory("Advanced")
        @Label("Debug Logging")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Enable detailed debug logging.")
        boolean debugLogging,

        @FormCategory("Advanced")
        @Label("Tag Path Delimiter")
        @FormField(FormFieldType.TEXT)
        @DefaultValue("")
        @Description("Character Ignition uses to parse a tag path into a tree view in the Power Chart and tag browser. "
                + "Leave empty (default) to show tags as a flat list (any '/' in the path is preserved with a special character so it is not split). "
                + "Set '/' to split the path into a hierarchical tree. "
                + "Set another character (e.g. '.') to build the tree by splitting on that character instead.")
        String delimiter
) {
    public FactryHistorianSettings toSettings() {
        FactryHistorianSettings settings = new FactryHistorianSettings();
        settings.setToken(token);
        settings.setUseTls(useTls);
        settings.setSkipTlsVerification(skipTlsVerification);
        settings.setCustomCaCert(customCaCert);
        settings.setDebugLogging(debugLogging);
        settings.setDelimiter(delimiter);
        return settings;
    }

    public static FactryHistorianConfig fromSettings(FactryHistorianSettings settings) {
        return new FactryHistorianConfig(
                settings.getToken(),
                settings.isUseTls(),
                settings.isSkipTlsVerification(),
                settings.getCustomCaCert(),
                settings.isDebugLogging(),
                settings.getDelimiter()
        );
    }
}
